#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:123456}
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_parking_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
#
#spring.data.redis.host=${REDIS_HOST:localhost}
#spring.data.redis.port=${REDIS_PORT:6379}
#spring.data.redis.password=${REDIS_PASSWORD:}
#
#logging.level.cn.gp.smartparking=${LOG_LEVEL:INFO}
#logging.file.name=${LOG_FILE_PATH:logs/smart-parking.log}
#
#websocket.port=${WEBSOCKET_PORT:8081}
