server:
  port: 10101
websocket:
  port: 10102

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_parking_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: smart_parking_platform
    password: mrWGz2WjaPammas4
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: OmXQGSyitwuI

#payment:
#  alipay:
#    notify-url: http://106.12.212.167:10101/smart-parking/api/alipay/notify
##    notify-url: http://106.12.212.167:10087/api/alipay/notify
#    return-url-web: http://106.12.212.167:10087/api/alipay/return
#    return-url-mobile: http://106.12.212.167:10087/api/alipay/mobile/return
#    web-pay-url: http://106.12.212.167:10087/api/alipay/web/pay
#    frontend-success-url: http://106.12.212.167:10087/
#    frontend-fail-url: http://106.12.212.167:10087/payfail

payment:
  alipay:
    notify-url: http://106.12.212.167:10101/smart-parking/api/alipay/notify
    return-url-web: http://106.12.212.167:10101/smart-parking/api/alipay/return
    return-url-mobile: http://106.12.212.167:10101/smart-parking/api/alipay/mobile/return
    web-pay-url: http://106.12.212.167:10101/smart-parking/api/alipay/web/pay
    frontend-success-url: http://106.12.212.167:10087/
    frontend-fail-url: http://106.12.212.167:10087/payfail