server:
  port: 9003
websocket:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_parking_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

# 开发环境日志配置
logging:
  level:
    cn.gp.smartparking: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# 支付宝支付
payment:
  alipay:
    notify-url: http://nc478447.natappfree.cc/smart-parking/api/alipay/notify
    return-url-web: http://localhost:9003/smart-parking/api/alipay/return
    return-url-mobile: http://localhost:9003/smart-parking/api/alipay/mobile/return
    web-pay-url: http://localhost:9003/smart-parking/api/alipay/web/pay
    frontend-success-url: http://localhost:5173/
    frontend-fail-url: http://localhost:5173/payfail


